defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: blog
    values:
      layout: blog
      preview: true
      type: article
      homelink:
        custom: page/blog/homelink.html
        tagline: Where a fox goes to ramble!
      css:
        - page/blog
      pagetitle: "<title> &nbsp;| &nbsp;Chiri's Blog"
  - scope:
      path: ""
      type: stories
    values:
      layout: story
      preview: true
      type: article
      css:
        - page/story
      pagetitle: "<title> &nbsp;— &nbsp;Chiri Vulpes"
  - scope:
      path: ""
      type: tags
    values:
      layout: tag
      homelink:
        custom: page/blog/homelink.html
        tagline: Where a fox goes to ramble!
      css:
        - page/blog
      pagetitle: "Chiri's Blog: Posts tagged with <title>"
      description: "See the blog posts tagged with <title>"

collections_dir: _collections
collections:
  blog:
    output: true
  tags:
    output: true
    permalink: /blog/:collection/:path:output_ext
  stories:
    output: true

sass:
  sass_dir: _includes/css

future: true
theme: null
exclude:
  - scss

# detach: false
