defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "blog"
      preview: true
      type: article
      homelink:
        custom: page/blog/homelink.html
        tagline: Where a fox goes to ramble!
      css:
        - page/blog

collections_dir: _collections
collections:
  blog:
    output: true

sass:
  sass_dir: _includes/css

future: true
theme: null
exclude:
  - scss

# detach: false
